---
apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: deploy helm chart
description: deploys a helm chart using a standard repo, non oci
inputs:
  chart_package:
    description: chart package
    required: true
  remote_repo:
    description: remote chart repository
    required: true
  remote_user_name:
    description: user name for the remote repo
    required: false
  remote_password:
    description: cred for te remote password
    required: false
  
runs:
  using: composite
  steps:
    - id: deploy_chart
      name: Deploy Chart
      uses: docker://alpine/helm:latest
      shell: sh
      run: |
        echo "abount to run [curl  -k -o /dev/null -u ${{ inputs.remote_password }}:${{ inputs.remote_user_name }} -w "%{http_code}" ${{ inputs.remote_repo }} --upload-file ${{ inputs.chart_package }}"
        resp=$(curl  -k -o /dev/null -u ${{ inputs.remote_user_name }}:${{ inputs.remote_password }} -w "%{http_code}" ${{ inputs.remote_repo }} --upload-file ${{ inputs.chart_package }})
        echo "response is *[$resp]*"
        if [ "$resp" == "200" ]
          then
          echo "************** upload ok with code [$resp]" 
        else
          echo "************** upload to nexus failed with code [$resp]"
          exit 1
        fi
           
